name: Build, Test, Run GitHub Action

on:
  push:
    branches:
    - dev

jobs:
  build_test_run:
    name: Build, test and run the GitHub Action
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        dotnet: [ '3.1.100' ]

    runs-on: ${{ matrix.os }}

    env:
      USER_AGENT: GitHubActionsPrMerge
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore NuGet packages
      shell: bash
      run: |
        dotnet restore

    - name: Build console app
      shell: bash
      run: |
        dotnet build

    - name: Test console app
      shell: bash
      run: |
        dotnet test test/**/*.csproj

    - name: Run the private action
      uses: ./
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        owner: justinyoo
        repository: github-pr-merge-action
        issueId: '7'
        mergeMethod: Squash
        commitTitle: ''
        commitDescription: ''
        deleteBranch: 'true'
